import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import ChartComponent from "../../components/Chart";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Festa Vendor | dasboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="z-50 text-white">
        <div className="z-50 py-5 border-b border-gray-200">
          <div className="z-30 -ml-4 -mt-2 flex items-center justify-between flex-wrap sm:flex-nowrap">
            <div className="z-30 ml-4 mt-2">
              <h3 className="text-2xl leading-6 font-medium text-white  ">
                Dasboard
              </h3>
            </div>
          </div>
        </div>

        <ChartComponent />
      </main>
    </>
  );
}
